services:
  - type: web
    name: vite-app
    env: static
    staticPublishPath: dist
    buildCommand: npm run build
    redirects:
      - source: "/*"
        destination: /index.html
        status: 200
